name: build-test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Diagnostics
        run: |
          echo "current directory $(pwd)"
          ls -la

      - name: Build
        working-directory: src
        run: go build -v ./...

      - name: Test
        working-directory: src
        run: go test -v ./...
